/**
 * Generate the framework detection injection script.
 * This script installs shims for React and Vue devtools hooks,
 * plus MutationObserver-based detection for Solid and Svelte.
 *
 * @param frameworks - Which frameworks to detect. If empty, returns empty string.
 */
export function getDetectionScript(frameworks: string[]): string {
	if (frameworks.length === 0) return "";

	const includeReact = frameworks.includes("react");
	const includeVue = frameworks.includes("vue");
	const includeSolid = frameworks.includes("solid");
	const includeSvelte = frameworks.includes("svelte");

	const parts: string[] = [];

	parts.push("(function() {");
	parts.push("  'use strict';");
	parts.push("");
	parts.push("  // __BL__ reporting helper");
	parts.push("  function blReport(type, data) {");
	parts.push("    try {");
	parts.push("      console.debug('__BL__', JSON.stringify({ type: type, ts: Date.now(), data: data }));");
	parts.push("    } catch (e) {}");
	parts.push("  }");
	parts.push("");

	if (includeReact) {
		parts.push("  // --- React detection via __REACT_DEVTOOLS_GLOBAL_HOOK__ ---");
		parts.push("  (function() {");
		parts.push("    var existing = window.__REACT_DEVTOOLS_GLOBAL_HOOK__;");
		parts.push("    var rendererCount = 0;");
		parts.push("    var reported = false;");
		parts.push("");
		parts.push("    function onInject(renderer) {");
		parts.push("      if (reported) return;");
		parts.push("      reported = true;");
		parts.push("      var version = 'unknown';");
		parts.push("      try {");
		parts.push("        if (renderer && renderer.version) version = String(renderer.version);");
		parts.push("        else if (renderer && renderer.reconcilerVersion) version = String(renderer.reconcilerVersion);");
		parts.push("        else if (typeof __REACT_VERSION__ !== 'undefined') version = String(__REACT_VERSION__);");
		parts.push("      } catch (e) {}");
		parts.push("      var bundleType = 0;");
		parts.push("      try {");
		parts.push("        if (renderer && typeof renderer.bundleType === 'number') bundleType = renderer.bundleType;");
		parts.push("      } catch (e) {}");
		parts.push("      var rootCount = 0;");
		parts.push("      try {");
		parts.push("        var hook = window.__REACT_DEVTOOLS_GLOBAL_HOOK__;");
		parts.push("        if (hook && hook.renderers) {");
		parts.push("          hook.renderers.forEach(function(r) {");
		parts.push("            try {");
		parts.push("              var roots = hook.getFiberRoots ? hook.getFiberRoots(r.rendererID || 1) : new Set();");
		parts.push("              rootCount += roots.size;");
		parts.push("            } catch (e) {}");
		parts.push("          });");
		parts.push("        }");
		parts.push("      } catch (e) {}");
		parts.push("      blReport('framework_detect', {");
		parts.push("        framework: 'react',");
		parts.push("        version: version,");
		parts.push("        rootCount: rootCount,");
		parts.push("        componentCount: 0,");
		parts.push("        bundleType: bundleType");
		parts.push("      });");
		parts.push("    }");
		parts.push("");
		parts.push("    if (existing) {");
		parts.push("      // Patch existing hook's inject method");
		parts.push("      var origInject = existing.inject;");
		parts.push("      existing.inject = function(renderer) {");
		parts.push("        var result = origInject ? origInject.call(this, renderer) : undefined;");
		parts.push("        onInject(renderer);");
		parts.push("        return result;");
		parts.push("      };");
		parts.push("    } else {");
		parts.push("      // Install minimal hook shim");
		parts.push("      var fiberRoots = {};");
		parts.push("      var renderers = new Map();");
		parts.push("      var hook = {");
		parts.push("        supportsFiber: true,");
		parts.push("        renderers: renderers,");
		parts.push("        inject: function(renderer) {");
		parts.push("          rendererCount++;");
		parts.push("          var id = rendererCount;");
		parts.push("          renderers.set(id, renderer);");
		parts.push("          renderer.rendererID = id;");
		parts.push("          fiberRoots[id] = new Set();");
		parts.push("          onInject(renderer);");
		parts.push("          return id;");
		parts.push("        },");
		parts.push("        onCommitFiberRoot: function(id, root, priorityLevel) {},");
		parts.push("        onCommitFiberUnmount: function(id, fiber) {},");
		parts.push("        getFiberRoots: function(id) {");
		parts.push("          return fiberRoots[id] || new Set();");
		parts.push("        },");
		parts.push("        checkDCE: function() {}");
		parts.push("      };");
		parts.push("      try {");
		parts.push("        Object.defineProperty(window, '__REACT_DEVTOOLS_GLOBAL_HOOK__', {");
		parts.push("          configurable: true,");
		parts.push("          enumerable: false,");
		parts.push("          get: function() { return hook; },");
		parts.push("          set: function(val) {");
		parts.push("            // If React DevTools installs its own hook later, let it, but wrap inject");
		parts.push("            if (val && typeof val.inject === 'function') {");
		parts.push("              var origInject2 = val.inject;");
		parts.push("              val.inject = function(renderer) {");
		parts.push("                var result = origInject2.call(this, renderer);");
		parts.push("                onInject(renderer);");
		parts.push("                return result;");
		parts.push("              };");
		parts.push("            }");
		parts.push("            hook = val;");
		parts.push("          }");
		parts.push("        });");
		parts.push("      } catch (e) {");
		parts.push("        window.__REACT_DEVTOOLS_GLOBAL_HOOK__ = hook;");
		parts.push("      }");
		parts.push("    }");
		parts.push("  })();");
		parts.push("");
	}

	if (includeVue) {
		parts.push("  // --- Vue detection via __VUE_DEVTOOLS_GLOBAL_HOOK__ ---");
		parts.push("  (function() {");
		parts.push("    var existing = window.__VUE_DEVTOOLS_GLOBAL_HOOK__;");
		parts.push("    var reported = false;");
		parts.push("");
		parts.push("    function onVueDetected(version, rootCount) {");
		parts.push("      if (reported) return;");
		parts.push("      reported = true;");
		parts.push("      blReport('framework_detect', {");
		parts.push("        framework: 'vue',");
		parts.push("        version: version || 'unknown',");
		parts.push("        rootCount: rootCount || 0,");
		parts.push("        componentCount: 0");
		parts.push("      });");
		parts.push("    }");
		parts.push("");
		parts.push("    if (existing) {");
		parts.push("      // Patch existing hook's emit method");
		parts.push("      var origEmit = existing.emit;");
		parts.push("      existing.emit = function(event, app, version) {");
		parts.push("        if (event === 'app:init') {");
		parts.push("          var ver = (app && app.version) ? app.version : (version || 'unknown');");
		parts.push("          onVueDetected(ver, existing.apps ? existing.apps.size : 1);");
		parts.push("        }");
		parts.push("        return origEmit ? origEmit.apply(this, arguments) : undefined;");
		parts.push("      };");
		parts.push("    } else {");
		parts.push("      // Install minimal Vue 3 hook shim");
		parts.push("      var listeners = {};");
		parts.push("      var hook = {");
		parts.push("        enabled: true,");
		parts.push("        apps: new Set(),");
		parts.push("        appRecords: [],");
		parts.push("        _buffer: [],");
		parts.push("        on: function(event, fn) {");
		parts.push("          if (!listeners[event]) listeners[event] = [];");
		parts.push("          listeners[event].push(fn);");
		parts.push("        },");
		parts.push("        once: function(event, fn) {");
		parts.push("          var self = this;");
		parts.push("          var wrapper = function() {");
		parts.push("            self.off(event, wrapper);");
		parts.push("            fn.apply(this, arguments);");
		parts.push("          };");
		parts.push("          this.on(event, wrapper);");
		parts.push("        },");
		parts.push("        off: function(event, fn) {");
		parts.push("          if (!listeners[event]) return;");
		parts.push("          listeners[event] = listeners[event].filter(function(f) { return f !== fn; });");
		parts.push("        },");
		parts.push("        emit: function(event, app, version) {");
		parts.push("          if (event === 'app:init') {");
		parts.push("            hook.apps.add(app);");
		parts.push("            var ver = (app && app.version) ? app.version : (version || 'unknown');");
		parts.push("            onVueDetected(ver, hook.apps.size);");
		parts.push("          }");
		parts.push("          var fns = listeners[event] || [];");
		parts.push("          for (var i = 0; i < fns.length; i++) {");
		parts.push("            try { fns[i].apply(null, Array.prototype.slice.call(arguments, 1)); } catch (e) {}");
		parts.push("          }");
		parts.push("        }");
		parts.push("      };");
		parts.push("");
		parts.push("      // Vue 2 detection via hook.Vue setter");
		parts.push("      var _Vue = null;");
		parts.push("      Object.defineProperty(hook, 'Vue', {");
		parts.push("        get: function() { return _Vue; },");
		parts.push("        set: function(Vue) {");
		parts.push("          _Vue = Vue;");
		parts.push("          if (Vue) {");
		parts.push("            var ver = (Vue.version) ? String(Vue.version) : 'unknown';");
		parts.push("            onVueDetected(ver, 0);");
		parts.push("          }");
		parts.push("        },");
		parts.push("        configurable: true");
		parts.push("      });");
		parts.push("");
		parts.push("      try {");
		parts.push("        Object.defineProperty(window, '__VUE_DEVTOOLS_GLOBAL_HOOK__', {");
		parts.push("          configurable: true,");
		parts.push("          enumerable: false,");
		parts.push("          get: function() { return hook; },");
		parts.push("          set: function(val) { hook = val; }");
		parts.push("        });");
		parts.push("      } catch (e) {");
		parts.push("        window.__VUE_DEVTOOLS_GLOBAL_HOOK__ = hook;");
		parts.push("      }");
		parts.push("    }");
		parts.push("  })();");
		parts.push("");
	}

	if (includeSolid || includeSvelte) {
		parts.push("  // --- Deferred detection for Solid/Svelte (no global hooks) ---");
		parts.push("  (function() {");
		parts.push("    var detected = { solid: false, svelte: false };");
		parts.push("    var deadline = Date.now() + 10000;");
		parts.push("");
		parts.push("    function checkDeferred() {");
		if (includeSolid) {
			parts.push("      // Solid detection");
			parts.push("      if (!detected.solid) {");
			parts.push("        var hasSolid = false;");
			parts.push("        try {");
			parts.push("          if (window._$SOLID || window.__SOLID_DEV__) hasSolid = true;");
			parts.push("          if (!hasSolid) {");
			parts.push("            var hkEls = document.querySelectorAll('[data-hk]');");
			parts.push("            if (hkEls && hkEls.length > 0) hasSolid = true;");
			parts.push("          }");
			parts.push("        } catch (e) {}");
			parts.push("        if (hasSolid) {");
			parts.push("          detected.solid = true;");
			parts.push("          blReport('framework_detect', {");
			parts.push("            framework: 'solid',");
			parts.push("            version: 'unknown',");
			parts.push("            rootCount: 0,");
			parts.push("            componentCount: 0");
			parts.push("          });");
			parts.push("        }");
			parts.push("      }");
		}
		if (includeSvelte) {
			parts.push("      // Svelte detection");
			parts.push("      if (!detected.svelte) {");
			parts.push("        var hasSvelte = false;");
			parts.push("        try {");
			parts.push("          var allEls = document.querySelectorAll('*');");
			parts.push("          for (var i = 0; i < Math.min(allEls.length, 100); i++) {");
			parts.push("            var el = allEls[i];");
			parts.push("            if (el.__svelte_meta || el.__svelte) { hasSvelte = true; break; }");
			parts.push("            if (el.constructor && el.constructor.prototype && el.constructor.prototype.__svelte_meta) { hasSvelte = true; break; }");
			parts.push("          }");
			parts.push("        } catch (e) {}");
			parts.push("        if (hasSvelte) {");
			parts.push("          detected.svelte = true;");
			parts.push("          blReport('framework_detect', {");
			parts.push("            framework: 'svelte',");
			parts.push("            version: 'unknown',");
			parts.push("            rootCount: 0,");
			parts.push("            componentCount: 0");
			parts.push("          });");
			parts.push("        }");
			parts.push("      }");
		}
		parts.push("      return detected.solid && detected.svelte;");
		parts.push("    }");
		parts.push("");
		parts.push("    // Check on DOM ready");
		parts.push("    if (document.readyState === 'loading') {");
		parts.push("      document.addEventListener('DOMContentLoaded', function() { checkDeferred(); });");
		parts.push("    } else {");
		parts.push("      checkDeferred();");
		parts.push("    }");
		parts.push("");
		parts.push("    // MutationObserver to catch late-loading frameworks");
		parts.push("    var observer = new MutationObserver(function(mutations) {");
		parts.push("      if (Date.now() > deadline) { observer.disconnect(); return; }");
		parts.push("      for (var i = 0; i < mutations.length; i++) {");
		parts.push("        var mutation = mutations[i];");
		parts.push("        if (mutation.type === 'childList') {");
		parts.push("          for (var j = 0; j < mutation.addedNodes.length; j++) {");
		parts.push("            if (mutation.addedNodes[j].nodeName === 'SCRIPT') {");
		parts.push("              checkDeferred();");
		parts.push("              break;");
		parts.push("            }");
		parts.push("          }");
		parts.push("        }");
		parts.push("      }");
		parts.push("      if (detected.solid && detected.svelte) observer.disconnect();");
		parts.push("    });");
		parts.push("    try {");
		parts.push("      observer.observe(document.documentElement || document.body, { childList: true, subtree: true });");
		parts.push("    } catch (e) {}");
		parts.push("  })();");
		parts.push("");
	}

	parts.push("})();");

	return parts.join("\n");
}
